version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: react-app
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: nest-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production